name: 'publish oomol package'
description: 'Publish oomol package by github action workflow'
runs:
  using: "composite"
  steps:
  - name: Install OIDC Client from Core Package
    run: npm install @actions/core@1.11.1 @actions/http-client
    shell: bash
  - name: Get Id Token
    uses: actions/github-script@v7
    id: id_token
    with:
      script: |
        const coredemo = require('@actions/core')
        let id_token = await coredemo.getIDToken()
        coredemo.setOutput('id_token', id_token)
  - name: Publish Oomol Package
    run: |
      mkdir -p /tmp/ooomol
      oopm install --token "github-action-${{ steps.id_token.outputs.id_token }}" -d /tmp/ooomol --registry "http://registry.oomol.dev"
      oopm thumbnail -s /tmp/ooomol
      oopm publish --token "github-action-${{ steps.id_token.outputs.id_token }}" --registry "http://registry.oomol.dev"
    shell: bash