name: 'publish oomol package'
description: 'Publish oomol package by github action workflow'
runs:
  using: "composite"
  steps:
  - name: Install OIDC Client from Core Package
    run: npm install @actions/core@1.11.1 @actions/http-client
    shell: bash
  - name: Get Id Token
    uses: actions/github-script@v7
    id: idtoken
    with:
      script: |
        const coredemo = require('@actions/core')
        let id_token = await coredemo.getIDToken()
        coredemo.setOutput('id_token', id_token)
  - name: Publish Oomol Package
    run: |
      oopm publish --token ${{ steps.idtoken.outputs.id_token }}
    shell: bash